insert into Club (nom, ville, pays, paysid) values ('chelsea fc','london','england', '7');
insert into Club (nom, ville, pays, paysid) values ('fc barcelone','barcelone','espagne', '7');
insert into Club (nom, ville, pays, paysid) values ('paris st germain','paris','france', '7');
insert into Club (nom, ville, pays, paysid) values ('bayern münich','münich','Deutschland', '7');
insert into Club (nom, ville, pays, paysid) values ('liverpool fc','liverpool','england', '7');
insert into Club (nom, ville, pays, paysid) values ('real madrid','madrid','espagne', '7');
insert into Club (nom, ville, pays, paysid) values ('arsenal','london','england', '7');
insert into Club (nom, ville, pays, paysid) values ('fc porto','porto','portugal', '7');
insert into Club (nom, ville, pays, paysid) values ('sc freiburg','freiburg','Deutschland', '7');
insert into Club (nom, ville, pays, paysid) values ('rb leipzig','leipzig','Deutschland', '7');
insert into Club (nom, ville, pays, paysid) values ('eintracht frankfurt','frankfurt','Deutschland', '7');
insert into Club (nom, ville, pays, paysid) values ('fc union berlin','berlin','Deutschland', '7');
insert into Club (nom, ville, pays, paysid) values ('borussia dortmund','dortmund','Deutschland', '7');
insert into Club (nom, ville, pays, paysid) values ('vfl wolfsburg','wolfsburg','Deutschland', '7');
insert into Club (nom, ville, pays, paysid) values ('borussia mönchengladbach','mönchengladbach','Deutschland', '7');
insert into Club (nom, ville, pays, paysid) values ('werder bremen','bremen','Deutschland', '7');
insert into Club (nom, ville, pays, paysid) values ('1.fsv mainz 05','mainz','Deutschland', '7');
insert into Club (nom, ville, pays, paysid) values ('tsg hoffenheim','hoffenheim','Deutschland', '7');
insert into Club (nom, ville, pays, paysid) values ('bayer 04 leverkusen','leverkusen','Deutschland', '7');
insert into Club (nom, ville, pays, paysid) values ('1. FC Köln','Köln','Deutschland', '7');
insert into Club (nom, ville, pays, paysid) values ('FC Augsburg','Augsburg','Deutschland', '7');
insert into Club (nom, ville, pays, paysid) values ('Hertha BSC','Hertha','Deutschland', '7');
insert into Club (nom, ville, pays, paysid) values ('VfB Stuttgart','Stuttgart','Deutschland', '7');
insert into Club (nom, ville, pays, paysid) values ('VfL Bochum','Bochum','Deutschland', '7');
insert into Club (nom, ville, pays, paysid) values ('FC Schalke 04','Essen','Deutschland', '7');
